# Generated by Django 5.0.6 on 2024-07-01 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("couple", "0003_wish_couple_wishes"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="couple",
            name="wishes",
        ),
    ]
